###############################################################################
# SIMPLE C TEMPLATE GENERATOR                                                 #
# Creates a basic C skeleton with boilerplate and headers                     #
# Assumes the C will be compiled on a Linux system.                           #
###############################################################################
from sys import argv
from datetime import datetime
from os import getcwd, mkdir
import argparse

'''
General settings
'''

COMMENT_BLOCK_COLUMN_SIZE           = 80
COMMENT_BLOCK_PRE_TEXT_BLANK_LINES  = 1
COMMENT_BLOCK_POST_TEXT_BLANK_LINES = 1


'''
ASM code stuff
'''

ASM_FUNC32_NAME = "asm_func_32"
ASM_FUNC32_DEFAULT_ARG = "0x12345"

ASM_FUNC64_NAME = "asm_func_32"
ASM_FUNC64_DEFAULT_ARG = "0x12345"

ASM32_SOURCE_SUFFIX = "%s_asm32.asm"
ASM64_SOURCE_SUFFIX = "%s_asm64.asm"
ASM32_OBJECT_SUFFIX = "%s_asm32.o"
ASM64_OBJECT_SUFFIX = "%s_asm64.o"

# global which is filled in using the constant + the stem
assembly_source_name_64 = ""
assembly_object_name_64 = ""

assembly_source_64 = """
;----------------------------------------------------------------------------;
; AUTOGENERATED ASSEMBLY SOURCE FILE BEGINS                                  ;
;----------------------------------------------------------------------------;
[BITS 64]
global %s

section .text

%s:
    mov     rax, rdi
    inc     rax
    retn
;----------------------------------------------------------------------------;
; AUTOGENERATED ASSEMBLY SOURCE FILE ENDS                                    ;
;----------------------------------------------------------------------------;
"""

assembly_prototype_64 = """
uint64_t %s( uint64_t arg1 );
"""

# global which is filled in using the constant + the stem
assembly_source_name_32 = ""
assembly_object_name_32 = ""

assembly_source_32 = """
;----------------------------------------------------------------------------;
; AUTOGENERATED ASSEMBLY SOURCE FILE BEGINS                                  ;
;----------------------------------------------------------------------------;
[BITS 32]
global %s

section .text

%s:
    push    ebp
    mov     ebp, esp
    mov     eax, dword[ebp+8]
    inc     eax
    pop     ebp
    retn
;----------------------------------------------------------------------------;
; AUTOGENERATED ASSEMBLY SOURCE FILE ENDS                                    ;
;----------------------------------------------------------------------------;
"""

assembly_prototype_32 = """
uint32_t %s( uint32_t arg1 );
"""

UTILITY_HEADER = "utils"
UTILITY_SOURCE = "utils"

'''
Utility code
'''

utility_header = """
#pragma once

#include <stdint.h>
#include <stdbool.h>

typedef struct _map
{
     int       map_fd;
     size_t    map_size;
     uint8_t*  map_ptr;
     bool      mapped;
}Map, *PMap;

bool convert_string_to_uint32_t( const char* in, uint32_t* out );
bool convert_string_to_uint64_t( const char* in, uint64_t* out );
bool convert_string_to_size_t( const char* in, size_t* out );
void hexdump( const uint8_t* buffer, const size_t size );
void hexdump_with_address( const uint8_t* buffer, const size_t size );
bool map_file( const char* filename, PMap m );
bool unmap_file( PMap m );
"""


utility_code = """
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <elf.h>

#include "utils.h"

bool convert_string_to_uint32_t( const char* in, uint32_t* out )
{
    char* endptr = NULL;
    errno = 0;
    uint32_t result = (uint32_t)strtoul( in, &endptr, 0 );
    if( in == endptr || *endptr || errno != 0 )
    {
        return false;
    }
    *out = result;
    return true;
}

bool convert_string_to_uint64_t( const char* in, uint64_t* out )
{
    char* endptr = NULL;
    errno = 0;
    uint64_t result = (uint64_t)strtoull( in, &endptr, 0 );
    if( in == endptr || *endptr || errno != 0 )
    {
        return false;
    }
    *out = result;
    return true;
}

bool convert_string_to_size_t( const char* in, size_t* out )
{
    char* endptr = NULL;
    errno = 0;
#if __SIZEOF_SIZE_T__ == __SIZEOF_LONG_LONG__
    unsigned long long result = strtoull( in, &endptr, 0 );
#else
    unsigned long result = strtoul( in, &endptr, 0 );
#endif
    if( in == endptr || *endptr || errno != 0 )
    {
        return false;
    }
    *out = (size_t)result;
    return true;
}

void hexdump( const uint8_t* buffer, const size_t size )
{
    size_t i = 0, j = 0;

    for( i = 0; i < size; i += 16 )
    {
        printf( "0x%08zX: ", i );
        for( j = 0; j < 16; j++ )
        {
            if( (i+j) < size )
            {
                printf( "%02X ", buffer[i+j] );
            }
            else
            {
                printf( "   " );
            }
        }
        printf( "        " );
        for( j = 0; j < 16; j++ )
        {
            if( (i+j) < size )
            {
                uint8_t temp = buffer[i+j];
                if( temp >= 0x20 && temp < 0x7F )
                {
                    printf( "%c", temp );
                }
                else
                {
                    printf( "." );
                }
            }
            else
            {
                printf( " " );
            }
        }
        printf( "\\n" );
    }
}

void hexdump_with_address( const uint8_t* buffer, const size_t size, const size_t address )
{
    size_t i = 0, j = 0;

    for( i = 0; i < size; i += 16 )
    {
        printf( "0x%08zX: ", address + i );
        for( j = 0; j < 16; j++ )
        {
            if( (i+j) < size )
            {
                printf( "%02X ", buffer[i+j] );
            }
            else
            {
                printf( "   " );
            }
        }
        printf( "        " );
        for( j = 0; j < 16; j++ )
        {
            if( (i+j) < size )
            {
                uint8_t temp = buffer[i+j];
                if( temp >= 0x20 && temp < 0x7F )
                {
                    printf( "%c", temp );
                }
                else
                {
                    printf( "." );
                }
            }
            else
            {
                printf( " " );
            }
        }
        printf( "\\n" );
    }
}

bool map_file( const char* filename, PMap m )
{
     int      temp_fd  = 0;
     uint8_t* temp_ptr = 0;
     struct stat s    = {0};

     if( ( temp_fd = open( filename, O_RDONLY ) ) < 0 )
     {
          printf( "Cannot open '%s' : errno %d\\n", filename, errno );
          return false;
     }


     if( fstat( temp_fd, &s ) < 0 )
     {
          printf( "Cannot stat '%s' : errno %d\\n", filename, errno );
          return false;
     }

     if( ( temp_ptr   = (uint8_t*)mmap( NULL, 
                                      s.st_size,
                                      PROT_READ,
                                      MAP_PRIVATE,
                                      temp_fd,
                                      0 ) ) == MAP_FAILED )
     {
          printf( "Cannot map '%s' : errno %d\\n", filename, errno );
          close( temp_fd );
          return false;
     }

     m->map_fd   = temp_fd;
     m->map_size = s.st_size;
     m->map_ptr  = temp_ptr;
     m->mapped   = true;

     return true;
}

bool unmap_file( PMap m )
{
     if( m->mapped == true )
     {
          munmap( m->map_ptr, m->map_size );
          close( m->map_fd );
          m->mapped = false;
     }
     return true;
}

"""

'''
Create the solid line /***...***/ which forms the beginning
and end of a C comment block
'''
def make_solid_line():
    result = "/"
    for i in range( 0, COMMENT_BLOCK_COLUMN_SIZE-2 ):
        result += "*"
    result += "/\n"
    return result


'''
Create a single line of C comment block, optionally with text
'''
def make_comment_line(text=''):
    result = "/* "
    result += "%s" % text
    while( len(result) < COMMENT_BLOCK_COLUMN_SIZE-2 ):
        result += " "
    result += "*/\n"
    return result


'''
Create the comment block for the C source file
'''
def make_comment_block(title, other_information=""):
    result =  make_solid_line()
    for i in range(1, COMMENT_BLOCK_PRE_TEXT_BLANK_LINES ):
        result += make_comment_line()
    result += make_comment_line(title)
    result += make_comment_line( datetime.now().strftime("%Y-%m-%d %H:%M:%S") )
    result += make_comment_line(other_information)
    for i in range(1, COMMENT_BLOCK_POST_TEXT_BLANK_LINES ):
        result += make_comment_line()
    result += make_solid_line()
    return result


'''
Create the includes block for the C source file
'''
def make_includes(includes=()):
    result =  "#include <stdio.h>\n"
    result += "#include <stdint.h>\n"
    result += "#include <stdlib.h>\n"
    result += "#include <string.h>\n"
    result += "#include <stdbool.h>\n"
    result += "#include <stddef.h>\n"
    result += "#include <unistd.h>\n" 
    for i in includes:
        result += "#include <%s>\n" % i
    return result


'''
Create the main() function for the C source file
'''
def make_main_function(filename, add_asm32_call=False, add_asm64_call=False):
    result =  "int main( int argc, char* argv[] )\n"
    result += "{\n"
    result += "     printf( \"%%s\\n\", \"%s\" );\n" % filename
    if( add_asm32_call == True ):
        result += "     printf( \"%%08X\\n\", %s(%s));\n" % ( ASM_FUNC32_NAME, ASM_FUNC32_DEFAULT_ARG )
    elif( add_asm64_call == True ):
        result += "     printf( \"%%016lX\\n\", %s(%s));\n" % ( ASM_FUNC64_NAME, ASM_FUNC64_DEFAULT_ARG )
    result += "     return 0;\n"
    result += "}\n\n"
    return result

'''
Create the main() function for the C source file - with call to file open
'''
def make_main_function_with_file_map(filename, add_asm32_call=False, add_asm64_call=False):
    result =  "int main( int argc, char* argv[] )\n"
    result += "{\n"
    result += "     int retVal = -1;\n"
    result += "     Map input = {0};\n"
    result += "\n"
    result += "     if( argc < 2 )\n"
    result += "     {\n"
    result += "          printf( \"Usage: \%s <inputfile>\\n\", argv[0]);\n"
    result += "          retVal = 0;\n"
    result += "          goto end;\n"
    result += "     }\n"
    result += "\n"
    result += "     if( map_file( argv[1], &input ) == false )\n"
    result += "     {\n"
    result += "          goto end;\n"
    result += "     }\n"
    result += "\n"
    if( add_asm32_call == True ):
        result += "     printf( \"%%08X\\n\", %s(%s));\n" % ( ASM_FUNC32_NAME, ASM_FUNC32_DEFAULT_ARG )
    elif( add_asm64_call == True ):
        result += "     printf( \"%%016lX\\n\", %s(%s));\n" % ( ASM_FUNC64_NAME, ASM_FUNC64_DEFAULT_ARG )
    result += "     retVal = 0;\n"
    result += "end:\n"
    result += "     unmap_file( &input );\n"
    result += "     return retVal;\n"
    result += "}\n\n"
    return result

'''
Create the Makefile
'''
def make_makefile(filestem, path_and_filename, files=[], has_asm32=False, has_asm64=False):
    global assembly_source_name_32
    global assembly_object_name_32
    global assembly_source_name_64
    global assembly_object_name_64
    extra_options = ""
    result = "all:\n\t"
    if( has_asm32 == True ):
        result += "nasm -felf32 -o %s %s\n\t" % ( assembly_object_name_32, assembly_source_name_32 )
        files.append( assembly_object_name_32 )
        extra_options += "-m32" # assume we're on a 64-bit system and need to tell gcc it should build the entire program as 32-bit
    elif( has_asm64 == True ):
        result += "nasm -felf64 -o %s %s\n\t" % ( assembly_object_name_64, assembly_source_name_64 )
        files.append( assembly_object_name_64 )

    result += "gcc -Wall -Werror %s -o %s " % ( extra_options, filestem )
    for i in files:
        result += "%s " % i
    result += "\n"
    # write it to the file
    try:
        with open( path_and_filename, "w+" ) as fh:
            fh.write(result)
    except Exception as e:
        print( "Error: %s\n" % e )
        return False
    
    return True


'''
Create a C source file
'''
def make_c_file(filestem, path_and_filename, include_header=False, include_utility=False, make_mapping=False, has_asm32=False, has_asm64=False):
    
    # assemble the file contents
    result =  make_comment_block(filestem)
    result += make_includes()
    if( include_header == True ):
        result += "#include \"%s.h\"\n" % filestem
    if( include_utility == True ):
        result += "#include \"%s.h\"\n" % UTILITY_HEADER
    result += "\n\n"

    # add asm function prototypes if necessary
    if( has_asm32 == True ):
        result += assembly_prototype_32 % ASM_FUNC32_NAME
        result += "\n\n"
    elif( has_asm64 == True ):
        result += assembly_prototype_64 % ASM_FUNC32_NAME
        result += "\n\n"

    if( include_utility == True and make_mapping == True ):
        result += make_main_function_with_file_map(filestem, has_asm32, has_asm64)
    else:
        result += make_main_function(filestem, has_asm32, has_asm64)

    # write it to the file
    try:
        with open( path_and_filename, "w+" ) as fh:
            fh.write(result)
    except Exception as e:
        print( "Error: %s\n" % e )
        return False

    return True

'''
Create a C header file
'''
def make_c_header(filestem, path_and_filename):
    # assemble the file contents
    result =  make_comment_block(filestem)
    result += '#pragma once\n\n'
    result += "\n\n"
    result += "#define AUTO_BUILD_NAME \"%s\"\n" % filestem
    result += "#define AUTO_BUILD_DATE \"%s\"\n" % ( datetime.now().strftime("%Y-%m-%d") )
    result += "#define AUTO_BUILD_TIME \"%s\"\n" % ( datetime.now().strftime("%H:%M:%S") )
    result += "\n\n"
    # write it to the file
    try:
        with open( path_and_filename, "w+" ) as fh:
            fh.write(result)
    except Exception as e:
        print( "Error: %s\n" % e )
        return False

    return True

'''
Create utility header
'''
def make_utility_header(filestem, path_and_filename):
    result = make_comment_block("UTILITY FUNCTIONS - AUTOGENERATED HEADER")
    result += "\n\n"
    result += utility_header

    # write it to the file
    try:
        with open( path_and_filename, "w+" ) as fh:
            fh.write(result)
    except Exception as e:
        print( "Error: %s\n" % e )
        return False

'''
Create utility code
'''
def make_utility_code(filestem, path_and_filename):
    result = make_comment_block("UTILITY FUNCTIONS - AUTOGENERATED SOURCE")
    result += "\n\n"
    result += utility_code

    # write it to the file
    try:
        with open( path_and_filename, "w+" ) as fh:
            fh.write(result)
    except Exception as e:
        print( "Error: %s\n" % e )
        return False

'''
Make 32-bit assembly source file
'''
def make_asm32_file(filestem, path_and_filename):
    result = assembly_source_32 % ( ASM_FUNC32_NAME, ASM_FUNC32_NAME )
    # write it to the file
    try:
        with open( path_and_filename, "w+" ) as fh:
            fh.write(result)
    except Exception as e:
        print( "Error: %s\n" % e )
        return False

'''
Make 64-bit assembly source file
'''
def make_asm64_file(filestem, path_and_filename):
    result = assembly_source_64 % ( ASM_FUNC64_NAME, ASM_FUNC64_NAME )
    # write it to the file
    try:
        with open( path_and_filename, "w+" ) as fh:
            fh.write(result)
    except Exception as e:
        print( "Error: %s\n" % e )
        return False

'''
The main() function - parse arguments, create directory, call other functions
'''
def main():
    global assembly_source_name_32
    global assembly_object_name_32
    global assembly_source_name_64
    global assembly_object_name_64
    parser = argparse.ArgumentParser()
    parser.add_argument("stem", help="Name of program. Source and header will be named this.")
    parser.add_argument( "-a", "--create_asm32", help="Add a 32-bit x86 assembly source file (requires NASM to build)", action="store_true")
    parser.add_argument( "-A", "--create_asm64", help="Add a 64-bit x86 assembly source file (requires NASM to build)", action="store_true")
    parser.add_argument( "-d", "--create_header", help="Add a header file", action="store_true")
    parser.add_argument( "-f", "--create_filemap", help="Add code to open the first argument as a mapped file (requires -u also)", action="store_true")
    parser.add_argument( "-m", "--create_makefile", help="Add a makefile", action="store_true")
    parser.add_argument( "-u", "--create_utility_functions", help="Add a file containing utility functions", action="store_true")

    args = parser.parse_args()

    has_asm32 = False
    has_asm64 = False
    has_makefile = False
    # get the current directory - we will make our directory here
    current_directory = getcwd()
    stem = args.stem


    file_list = []
    path = current_directory + '/' + stem
    mkdir(path) 
    c_source_path_filename = "%s/%s.c" % ( path, stem )
    file_list.append( "%s.c" % stem )
    c_header_path_filename = ""
    makefile_path_filename = ""

    # assume if we're creating utility functions then we also want a makefile
    if args.create_utility_functions:
        utility_header_path_filename = "%s/%s.h" % ( path, UTILITY_HEADER )
        utility_code_path_filename   = "%s/%s.c" % ( path, UTILITY_SOURCE )
        file_list.append( "%s.c" % UTILITY_SOURCE )

        if( make_utility_header( stem, utility_header_path_filename ) == False ):
            print( "Error creating utility header file" )
            exit(-1)
        
        if( make_utility_code( stem, utility_code_path_filename ) == False ):
            print( "Error creating utility source code file" )
            exit(-1)
        has_makefile = True

    if args.create_header:
        c_header_path_filename = "%s/%s.h" % ( path, stem )

    # only necessary if a bare C file is being created    
    if args.create_makefile:
        has_makefile = True
        

    # assume if we're creating assembly source then we need a makefile 
    if args.create_asm32:
        assembly_source_name_32 = ASM32_SOURCE_SUFFIX % stem
        assembly_object_name_32 = ASM32_OBJECT_SUFFIX % stem
        if( make_asm32_file( stem, "%s/%s" % ( path, assembly_source_name_32 ) ) == False ):
            print( "Error creating 32-bit assembly source file" )
            exit(-1)
        has_asm32 = True
        has_makefile = True

    elif args.create_asm64:
        assembly_source_name_64 = ASM64_SOURCE_SUFFIX % stem
        assembly_object_name_64 = ASM64_OBJECT_SUFFIX % stem
        if( make_asm64_file( stem, "%s/%s" % ( path, assembly_source_name_64 ) ) == False ):
            print( "Error creating 64-bit assembly source file" )
            exit(-1)
        has_asm64 = True
        has_makefile = True

    if( make_c_file( stem, c_source_path_filename, args.create_header, args.create_utility_functions, args.create_filemap, has_asm32, has_asm64 ) == False ):
        print( "Error creating C source file" )
        exit(-1)

    if( args.create_header ):
        if( make_c_header( stem, c_header_path_filename ) == False ):
            print( "Error creating header file" )
            exit(-1)

    if( has_makefile == True ):
        makefile_path_filename = "%s/Makefile" % path
        if( make_makefile( stem, makefile_path_filename, file_list, has_asm32, has_asm64 ) == False ):
            print( "Error creating Makefile" )
            exit(-1)

    print( "[Ok]" ) 


if __name__ == "__main__":
    main()